### ISSUE TITLE
falling off the starting ledge (go left, then right) results in segfault

### ISSUE THREAD

**Issue by lowagner** [makapuf/bitbox-0xFF#1]
but it was a very fun visual experience.

**Comment by makapuf** [comment]
Hey thanks for giving an eye !
Yes it's funny you can even go through sprites as a tilemap...

Le 23 juil. 2016 7:11 PM, "Lucas O. Wagner" notifications@github.com a
écrit :

**Comment by makapuf** [comment]
note that now the levels are "boxed" with a 2D box so you cant go out of them.
