### ISSUE TITLE
defs.h could be produced by Makefile

### ISSUE THREAD

**Issue by lowagner** [makapuf/bitbox-0xFF#2]
here's a sample Makefile, though as you wish--

```
NAME := 0xFF

DEFINES += VGAMODE_320
#DEFINES += DISABLE_ESC_EXIT

GAME_C_FILES= main.c graph.c loader_sd.c mappers.c
#USE_SAMPLER=1
USE_SDCARD = 1
# if not usesdcard, use loader_flash + make data

everything: all defs.h

include $(BITBOX)/lib/bitbox.mk

defs.h: REFERENCE.md
▸   ./mk_defs.py REFERENCE.md > $@

todo: main.c graph.c loader_sd.c
▸   grep -n TODO $^

.PHONY: todo
clean::
▸   rm -f defs.h
```

**Comment by makapuf** [comment]
well (did not test it) but the autodependencies flags generated by gcc for .h from .c  _should_ handle it automatically. if not it's maybe bitbox.mk that needs fixing.

**Comment by makapuf** [comment]
yup, definitely is generated auto AFAIK. not closing, let's investigate

**Comment by makapuf** [comment]
maybe something to do with commit fix https://github.com/makapuf/bitbox/commit/47d19375c22bfdfd6015d7a50453c0dcca73d2fb from bitbox tree

**Comment by makapuf** [comment]
well, it happened that autodeps from gcc works if the project can compile, which is does if defs.h existed ..  explicited defs.h making to make it work the first time.
